version: '3.8'

services:
  web:
    build: .
    command: gunicorn motorista_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A motorista_project worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
