# Generated by Django 5.2.4 on 2025-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('veiculo', models.CharField(choices=[('MOTO', 'Moto'), ('HATCH', 'Carro Hatch'), ('SEDAN', 'Carro Sedan'), ('CAMINHONETE', 'Caminhonete')], max_length=20)),
            ],
        ),
    ]
